# .github/workflows/sentry-upload.yml
name: Upload sourcemaps to Sentry

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - uses: getsentry/action-release@v1
        with:
          environment: production
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: PPL-5B
          SENTRY_PROJECT: javascript-nextjs
          SENTRY_URL: https://sentry.io/